### ISSUE TITLE
Add a check whether all previous matches are reported before pairing next rounds

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#107]
A very rare incident occured in PDM just now.
Start of 1st round 
![image](https://user-images.githubusercontent.com/13656154/40334707-5757d12a-5d9a-11e8-9796-3308b4994ed1.png)

14 mins later while r1 is still under way, the system pairs r2 matches
![image](https://user-images.githubusercontent.com/13656154/40334723-679e29d0-5d9a-11e8-828c-11ecb2b56852.png)

1 min after that, it pairs the r3
![image](https://user-images.githubusercontent.com/13656154/40334749-88957788-5d9a-11e8-9967-c18f54bde61f.png)

And the event setting shows that the current round is on round 3, which means the pairinf code did fire twice,

We have deleted the r2 and 3 pairings and return the setting to r1

**Comment by silasary** [comment]
Without screenshots of the Gatherling interface, I can't even begin to guess at what happened there.

**Comment by stash86** [comment]
All we know are
1. The Current Round setting is at '3'
2. The pairings does posted in the Match Listing tab

Other than that, sadly tom and briar didn't screenshot anything

**Comment by stash86** [comment]
But I think it's easy to add a check before we let the code pair the next round, isn't it? That would close this issue without you need to dive into it
