### ISSUE TITLE
Events fail mysteriously if they don't have a cohost.

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#11]
So I tried to create an event with a custom name and with the automatic naming, both ends up with no event created

Automatic naming
![auto name](https://user-images.githubusercontent.com/13656154/33107449-b27f7fe8-cf7a-11e7-911b-b52c7d4fd7c4.png)

Custom naming
![custom name](https://user-images.githubusercontent.com/13656154/33107451-b2d04144-cf7a-11e7-9edb-e4d2046d0573.png)

What I get after I hit create button
![image](https://user-images.githubusercontent.com/13656154/33107487-d6add87e-cf7a-11e7-979d-0f1892af2b47.png)

How my Host CP look like after hit the create button
![image](https://user-images.githubusercontent.com/13656154/33107536-0c4ca776-cf7b-11e7-827e-73d09fb8464b.png)

**Comment by silasary** [comment]
>  Cannot add or update a child row: a foreign key constraint fails (`gatherling`.`events`, CONSTRAINT `events_ibfk_4` FOREIGN KEY (`cohost`) REFERENCES `players` (`name`) ON UPDATE CASCADE)
