### ISSUE TITLE
Still can't create event

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#13]
Event setting
![screenshot-2017-11-22 gatherling pennydreadfulmagic com event host control panel](https://user-images.githubusercontent.com/13656154/33113399-87bba43c-cf9b-11e7-8f56-37606253ce73.png)

What I got
Field 'current_round' doesn't have a default value

**Comment by silasary** [comment]
Argh.  I'd already fixed that before I merged LTG's code in.

Let me reapply the fix.
