### ISSUE TITLE
Event setting: Allow late registration

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/gatherling_fork#15]
We have a lot of people who either show up after 10am, but before Round 1 fires, or after round 1 fires, but before round two fires. (Average of 2 per tournament)

Add event setting to allow people to self-register after 'pre-reg' ends, but before round X starts.

**Comment by longtimegone** [comment]
This should be simple enough, all the code for adding a late player exists, we just need to alter the code that displays upcoming matches to continue to display the active ones that are in late registration mode.

**Comment by silasary** [comment]
0895cf521c27e3ca793e4aadcbfc9fba52aceff8
