### ISSUE TITLE
Display times in User's local Timezone

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/gatherling_fork#3]
This would be nice.  (Requires porting default times to UTC)

**Comment by stash86** [comment]
Wonder if this is what you want. So if I have an event that is scheduled for Wed, 3 Oct 2018 05:30 AM EST, 

if I'm on UTC-12 timezone, my Player CP will show
PREREGISTER FOR EVENTS--
Standard Crazyness 1.04 | 02 Oct 2018 21:30:00 | Register

But for those on UTC+9, it will show
PREREGISTER FOR EVENTS--
Standard Crazyness 1.04 | 03 Oct 2018 18:30:00 | Register

So instead of the time interval to that event, it will shows the start time in user's local time and date

**Comment by bakert** [comment]
Time interval is best when the time is imminent because it's unambiguous
and doesn't rely on browser settings to get it right.

But there are plenty of places where the New York time shows. Where those
are non-admin pages that should be replaced with localized versions.

**Comment by stash86** [comment]
I'm using the timezone in the player setting, not the player's computer timezone, So if they messed that up, their own risk 🗡

I can put the interval in the mouse tooltip or vice versa I guess....

**Comment by stash86** [comment]
For now, I only changed the PREREGISTER FOR EVENTS section on the Player CP page

**Comment by bakert** [comment]
I just want to go on record as saying I think this is a mistake. I actually
think browser is more likely to be correct. Did you check what timezones
are in the db? How many are set to the default?

**Comment by silasary** [comment]
As a user in the southern hemisphere, I am strongly opposed to using the profile field.

Even if I do set it correctly, there is a potential for ±2 hours in difference between my registered timezone and the actual interval. (Depending on whether zero, one or both of the US DST and Aus DST changes are currently active).

Please please please rely on browser settings.

**Comment by stash86** [comment]
After testing my hack with supposed Melbourne UTC equivalent, I can see the problem.

**Comment by stash86** [comment]
Can both of you can go to http://helhalmshop.tk/tes.php and check whether it's correct or not?

I need to check whether the script get your local timezone correctly, and whether the 2 sample cases I have are converted correctly as well

Thanks

On 19 Aug 2018, at 16.36, Katelyn Gigante <notifications@github.com> wrote:

As a user in the southern hemisphere, I am strongly opposed to using the profile field.

Even if I do set it correctly, there is a potential for ±2 hours in difference between my registered timezone and the actual interval. (Depending on whether zero, one or both of the US DST and Aus DST changes are currently active).

Please please please rely on browser settings.
