### ISSUE TITLE
remove /me from the beginning of pairings' rows

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#33]
So instead of
/me Pairings for Round 1
/me Fred_Dettofano 2-1 br_laern
/me maCHOOga 2-0 AEFabricio
/me RedderTory 2-1 stash86
/me mathguy31415 2-0 gutvip
/me BowynArrow 2-0 morpphling
/me tomsimons vs. Yokai_
/me Good luck everyone!

we get this instead
Pairings for Round 1
Fred_Dettofano 2-1 br_laern
maCHOOga 2-0 AEFabricio
RedderTory 2-1 stash86
mathguy31415 2-0 gutvip
BowynArrow 2-0 morpphling
tomsimons vs. Yokai_
Good luck everyone!

**Comment by silasary** [comment]
Sounds good.
The /me bits are an anachronism from the V3 days
