### ISSUE TITLE
Make the player's result submission form looked like in Host CP

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#35]
So instead of the 4 bulleted option, we have

Player A  "drop down option"  Player B.

I don't know why, but we keep getting 1 wrong submission per event lately, even from veteran gatherling players, so I hope the new layout would make it more straightforward.

**Comment by stash86** [comment]
I'm closing this because the dropdown version isn't that clearer, as sometimes TO made mistakes when inputting manual results

**Comment by silasary** [comment]
Agreed.  The TO view is downright confusing, and I tolerate it only because it needs to be compact when running 50-player rounds (looking at you, Pauper)
