### ISSUE TITLE
Links for events on Recent Decks section is wrong

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#44]
This is what I get from the Recent Decks section
http://gatherling.com/event.php?event=Vintage+MTGO+Swiss+6.63

The above link is for host, hence non-host will get this error
You are not permitted to make that change. Please contact the event host to modify this event. If you are the event host, or feel that you should have privilege to modify this event, you should contact Dabil via the Pauper Krew forums.

The correct link should be
http://gatherling.com/eventreport.php?event=Vintage+MTGO+Swiss+6.63

**Comment by silasary** [comment]
The link changes itself based on whether you are a host or not.

If you are not a host, it'll link to eventreport as normal 😄

**Comment by silasary** [comment]
Turns out the above code was misbehaving.  Fixed by switching to $event->authCheck() instead.
