### ISSUE TITLE
Make a really dodgy name for a deck if a User doesn't submit one

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/gatherling_fork#5]
> if user doesn’t input deck name, it would take the color of the deck and the archetype as the deck’s name. It would help a lazy player like me

**Comment by silasary** [comment]
Done.

**Comment by bakert** [comment]
You could use the logic from deck_name.py – it uses colors and archetype (if known) to form a name.

**Comment by silasary** [comment]
Yeah, that's essentially what we do.  Except that Gatherling's idea of Archetype is much more basic than PDM's.

So this code will mostly end in `W Unclassified` or the like.
