### ISSUE TITLE
Make the rules for ending sessions much less strict

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/gatherling_fork#56]
As it stands people generally have to login once per round at a minimum and get messages about changing IP and such. Let's have cookies last at least 24 hours if not 5 years and not care about IP addresses.

Relatedly we should make sure account recovery works if we're not going to force people to type their password constantly :D

**Comment by silasary** [comment]
This was partially fixed with 4.8.0, and finished with b2fc3a7f23512ee80244d81bc58c344547209abb.

Account recovery still needs to happen, but I have it as high priority in #28
