### ISSUE TITLE
"Recent decks" no longer populates on gatherling event signup pages

### ISSUE THREAD

**Issue by Swaskowi** [PennyDreadfulMTG/gatherling_fork#62]
When registering for an event, it no longer cache's previous entries in the drop down bar to allow quick registration.

![image](https://user-images.githubusercontent.com/595670/36287284-e522bd1c-1281-11e8-8bde-eb429662e0bc.png)

Chrome Version 63.0.3239.132, Briar_moss account.  

Not very impactful personally just wanted to report in case it was inadvertant and unknown.

**Comment by silasary** [comment]
Fixed in  86409eb
