### ISSUE TITLE
The result reporting system don't take into verification who is the opponent?

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#67]
So this is the case:
Player A vs Player B. Last match of round 1. Player A won 2-1. Player B has input his/her result. Then Player A input his result (2-1 win). hiThis is where the error started

1. The system register the win correctly (Player A 2-1 Player B)
2. The system did the pairing for Round 2
3. The system then register another result for Player A (Player A won 2-1 vs Player C). Luckily it's the one-sided report, so easily fixed and can be revised by the players later.

So the question is, when I click Submit Result button, there is no data sent to the systen about who was my opponent?

**Comment by bakert** [comment]
This would match with my experience of submitting results at the same time as players when it's the last result of the round. Good spot.
