### ISSUE TITLE
"Edit Deck" button shown if I look at a decklist as a guest (not logged in)

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#72]
Somehow if I look at a decklist in "guest" mode, the Edit Deck button is shown. When I click on it, it will ask me to log in, so no security hole, but it just seems weird to have it shown there.

**Comment by silasary** [comment]
Can't reproduce?

**Comment by stash86** [comment]
You might have fixed it with the previous update :D
