### ISSUE TITLE
Put the name of the tournament you are registering for on the deck registration page

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/gatherling_fork#75]
@Tom (bakert99) i think it might be a good idea to put the tournament you're registering for on the deck registration screen on gatherling because i apparently accidentally registered for heirloom without realizing - it's definitely user error in this case b/c i wasnt paying attention - but it might be useful kinda like the confirmation screen for reporting matches

-- thelonesun

**Comment by stash86** [comment]
Added in #126 PR
