### ISSUE TITLE
mtgjson removes jvc.json file

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#83]
So I'm in process of importing the card sets, and I get this error on JVC set

> Warning: file_get_contents(https://raw.githubusercontent.com/mtgjson/mtgjson/master/json/JVC.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\gatherling\util\insertcardset.php on line 27

Going to mtgjson github page, it seems like they have removes jvc.json, and they have DD3_JVC.json instead

**Comment by stash86** [comment]
Okay, so far what I found is these changes

JVC -> DD3_JVC
NEM -> NMS
PHPR -> pMEI

**Comment by silasary** [comment]
The cause here is a bit more complex, but yeah, it's a known thing.  I'll add the corrections to the process.
