### ISSUE TITLE
The first event created for a new series using the floating notification will assign a "0.01" name to the new event

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#85]
This is in my local env, using the latest dev branch

So I just created a new format named "Modern Madness". As expected, the floating notification will ask me if I want to create a new event for it.

![image](https://user-images.githubusercontent.com/13656154/38547083-40eee3aa-3ce9-11e8-8951-665c088fcb46.png)

If I click on it, this is what I get
![image](https://user-images.githubusercontent.com/13656154/38547120-5af9290e-3ce9-11e8-82fd-a5d3b6dd4c47.png)

No option to rename the event

**Comment by silasary** [comment]
Ah, the "Create next event" flow doesn't work properly when there isn't a previous event in the series to use.
