### ISSUE TITLE
Floating bar ask me to create upcoming event while I'm running the current event

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#89]
So while I'm in the action of running the latest PDT, the action bar keeps reminding me to create next event. I don't think you want to encourage TOs to create as many advance events like Tom does 😈 

![image](https://user-images.githubusercontent.com/13656154/38710796-141afcf4-3efd-11e8-991b-b0618c6cbab3.png)

**Comment by silasary** [comment]
This is 100% the intended behaviour.

Often, TOs don't log into gatherling during the week, and are only around on event day.  

Creating the following week's event during a downtime in this week's event is therefore the best time to do it.

**Comment by bakert** [comment]
Pretty sure creating (multiple) events in advance is the only sane thing to
do under the current system.

Better UI for players regardless of the number of future events and the
ability to say “this event is on every week until I say not” would be
sweet, though.
