### ISSUE TITLE
Add feature to be able to upload txt file for Restricted, Banned, and Legal list

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/gatherling_fork#97]
I think I can do this, but I wonder whether any of you have any concern with that?

Being able to upload legal cards for PD and heirloom in a single click is a good improvement :D

**Comment by silasary** [comment]
Go for it

**Comment by bakert** [comment]
Will it still choke on the first illegal card? Or skip and report them all at once? Because the latter would be good!

**Comment by stash86** [comment]
The latter. I have tested it, and it will list all failed card(s) and the reason why it fails

**Comment by bakert** [comment]
Sweet. Push it!
